version: '3'
services:
  php:
    image: 192744901475.dkr.ecr.ap-northeast-1.amazonaws.com/production-sample-app/php:
    env_file:
      - .env
    ports:
      - "9000:9000"
    command: php-fpm
  nginx:
    image: 192744901475.dkr.ecr.ap-northeast-1.amazonaws.com/production-sample-app/nginx:
    env_file:
      - .env
    ports:
      - "80:80"
    command: /usr/sbin/nginx -g 'daemon off;'
